"use client";

import { useState, useRef, useCallback, type KeyboardEvent } from "react";
import { cn } from "@/lib/utils";
import { ProviderSelector } from "./provider-selector";
import type { ProviderId, ProviderConfigClient } from "@/types/provider";

interface MessageComposerProps {
  onSend: (content: string) => void;
  isLoading: boolean;
  selectedProvider: ProviderId;
  selectedModel: string;
  onProviderChange: (providerId: ProviderId, modelId: string) => void;
  configuredProviders: ProviderConfigClient[];
  onStop?: () => void;
}

export function MessageComposer({
  onSend,
  isLoading,
  selectedProvider,
  selectedModel,
  onProviderChange,
  configuredProviders,
  onStop,
}: MessageComposerProps) {
  const [input, setInput] = useState("");
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const handleSubmit = useCallback(() => {
    const trimmed = input.trim();
    if (!trimmed || isLoading) return;
    onSend(trimmed);
    setInput("");
    if (textareaRef.current) {
      textareaRef.current.style.height = "auto";
    }
  }, [input, isLoading, onSend]);

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  return (
    <div className="border-t border-border-subtle bg-background/80 backdrop-blur-sm">
      <div className="max-w-3xl mx-auto px-4 py-4">
        <div
          className={cn(
            "rounded-2xl border border-border bg-surface",
            "focus-within:border-zinc-600 transition-colors duration-150"
          )}
        >
          <textarea
            ref={textareaRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Send a message..."
            rows={1}
            className={cn(
              "w-full resize-none bg-transparent px-4 pt-4 pb-2 text-sm text-zinc-100",
              "placeholder:text-zinc-500 focus:outline-none",
              "textarea-auto"
            )}
          />

          <div className="flex items-center justify-between px-3 pb-3">
            <ProviderSelector
              selectedProvider={selectedProvider}
              selectedModel={selectedModel}
              onSelect={onProviderChange}
              configuredProviders={configuredProviders}
            />

            <div className="flex items-center gap-2">
              {isLoading && onStop && (
                <button
                  type="button"
                  onClick={onStop}
                  className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs text-zinc-400 hover:text-zinc-200 bg-surface-raised border border-border transition-colors"
                >
                  <svg className="h-3 w-3" viewBox="0 0 16 16" fill="currentColor">
                    <rect x="3" y="3" width="10" height="10" rx="2" />
                  </svg>
                  Stop
                </button>
              )}
              <button
                type="button"
                onClick={handleSubmit}
                disabled={!input.trim() || isLoading}
                className={cn(
                  "rounded-xl p-2 transition-all duration-150",
                  input.trim() && !isLoading
                    ? "bg-accent text-zinc-950 hover:bg-accent-hover active:scale-[0.95]"
                    : "bg-zinc-800 text-zinc-500 cursor-not-allowed"
                )}
              >
                <svg
                  className="h-4 w-4"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M5 12h14M12 5l7 7-7 7" />
                </svg>
              </button>
            </div>
          </div>
        </div>

        <p className="text-center text-[11px] text-zinc-600 mt-2.5">
          Responses generated by your selected AI provider using your API key
        </p>
      </div>
    </div>
  );
}
